name: Generate Pixel Profile Card

on:
  # se ejecuta automáticamente todos los días a las 6:00 UTC
  schedule:
    - cron: "0 6 * * *"
  # también lo podés correr manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create assets folder
        run: mkdir -p assets

      # Genera tarjeta CRT para modo claro
      - name: Generate CRT light
        run: curl -L "https://pixel-profile.vercel.app/api/github-stats?username=fcreme&theme=crt" -o assets/pixel-stats-light.svg

      # Genera tarjeta CRT para modo oscuro (con efecto pantalla)
      - name: Generate CRT dark
        run: curl -L "https://pixel-profile.vercel.app/api/github-stats?username=fcreme&theme=crt&screen_effect=true" -o assets/pixel-stats-dark.svg

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pixel stats"
          file_pattern: "assets/pixel-stats-*.svg"
